### ISSUE TITLE
Morning session.

### ISSUE THREAD

**Issue by balerum03** [pipe2442/Using-Bootstrap-#1]
Your page looks amazing as it is but to make it look even better you can consider implementing this:
- try to change the width on the navbar.
- change columns so that it looks better on all viewports.
- use more semantic HTML.
- Consider including some of the adds that are on the original page.
- You could change the logo with an SVG tag
- In the debate section, you are missing the VS thingy.

**Comment by pipe2442** [comment]
Thanks for your advice guys!
